- name: check if a reboot is required
  register: reboot_required_file
  stat: path=/var/run/reboot-required

- name: reboot the server
  shell: sleep 4 && shutdown -r now 'Reboot triggered by Ansible'
  async: 1
  poll: 0
  when: reboot_required_file.stat.exists == true

- name: wait for server to be alive
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=10 timeout=300
  become: no
  when: reboot_required_file.stat.exists == true
