- name: ensure binary is present
  unarchive:
    src: "{{download_url}}"
    dest: "{{install_dir}}"
    remote_src: yes

- name: ensure mlock syscall can be used without root access
  capabilities:
    capability: cap_ipc_lock=+ep
    path: "{{install_dir}}/{{name}}"

- name: ensure user exists
  user:
    name: "{{user}}"
    groups: ""

- name: ensure needed directories exist
  file:
    path: "{{config_dir}}"
    state: directory

- name: ensure configuration is in place
  template:
    src: server.hcl.j2
    dest: "{{config_dir}}/server.hcl"
  ignore_errors: yes

- name: ensure service has been installed
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/{{name}}.service
  ignore_errors: yes

- name: ensure service has been enabled/is running
  systemd:
    name: "{{name}}"
    enabled: yes
    state: started
    daemon_reload: yes

- name: ensure VAULT_ADDR is set so vault cli works without -address flag
  lineinfile:
    insertbefore: BOF
    state: present
    line: VAULT_ADDR=http://{{ansible_default_ipv4.address}}:8200
    dest: /etc/environment
    create: yes
