- name: add keys to apt
  apt_key:
    id: "{{item}}"
    keyserver: hkp://p80.pool.sks-keyservers.net
    state: present
  with_items:
   - 58118E89F3A912897C070ADBF76221572C52609D

- name: add ppas to apt
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items:
    - deb https://apt.dockerproject.org/repo ubuntu-xenial main

- name: ensure apt packages are installed
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - docker-engine

- name: adding user nomad to docker group
  user: name='nomad'
        groups=docker
        append=yes
