- name: ensure consul binary is present
  unarchive:
    src: "{{download_url}}"
    dest: "{{install_dir}}"
    remote_src: yes

- name: ensure user exists
  user:
    name: "{{user}}"
    groups: ""

- name: ensure needed directories exist
  file:
    path: "{{item}}"
    owner: "{{user}}"
    group: "{{group}}"
    state: directory
  with_items:
    - "{{data_dir}}"
    - "{{config_dir}}"

- name: ensure service has been installed
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/{{name}}.service
  ignore_errors: yes
