- name: update apt cache and installed packages
  apt:
    update_cache: yes
    upgrade: yes

- name: install base packages
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - apt-transport-https
    - ca-certificates
    - python-pip
    - unzip
    - jq
    - mc
    - vim
    - wget
    - tcpdump
    - htop
    - sysstat
    - psmisc
    - ntp
    - dnsutils


- name: ensure ntp service is enabled and running
  systemd:
    name: ntp
    enabled: yes
    state: started
